#!/bin/bash
# extract-th-schemas.sh - Extract TH AST from GHC releases and convert to GraphQL
# Usage: ./extract-th-schemas.sh [GHC_REPO] [OUTPUT_DIR]
set -uo pipefail

GHC_REPO="${1:-/mnt/data1/2023/07/05/ghc}"
OUTDIR="${2:-$(pwd)/docs/ghc-schemas}"
SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
mkdir -p "$OUTDIR"

echo "GHC repo: $GHC_REPO"
echo "Output:   $OUTDIR"
echo ""

# Find latest release tag per major version
cd "$GHC_REPO"
TAGS=""
for maj in 9.2 9.4 9.6 9.8 9.10 9.12 9.14; do
  tag=$(git tag | grep -E "^ghc-${maj}\.[0-9]+-release$" | sort -V | tail -1)
  [ -n "$tag" ] && TAGS="$TAGS $tag"
done

echo "Tags: $TAGS"
echo ""

# Extract TH Syntax.hs from each tag
for tag in $TAGS; do
  ver=$(echo "$tag" | sed 's/ghc-\(.*\)-release/\1/')
  thfile="$OUTDIR/th-syntax-${ver}.hs"
  # GHC 9.12+ moved types to GHC.Internal.TH.Syntax
  git show "$tag:libraries/ghc-internal/src/GHC/Internal/TH/Syntax.hs" > "$thfile" 2>/dev/null
  if [ ! -s "$thfile" ] || [ "$(wc -l < "$thfile")" -lt 100 ]; then
    git show "$tag:libraries/template-haskell/Language/Haskell/TH/Syntax.hs" > "$thfile" 2>/dev/null
  fi
  if [ -s "$thfile" ]; then
    echo "$ver: $(wc -l < "$thfile") lines"
  else
    echo "$ver: MISSING"
    rm -f "$thfile"
  fi
done

echo ""
echo "=== Converting to GraphQL schemas ==="

# Parse Haskell data types and emit GraphQL SDL
hs_to_graphql() {
  local infile="$1"
  python3 -c "
import re, sys

lines = open('$infile').readlines()
src = ''.join(lines)

# Extract data declarations
# Match: data Name = Con1 ... | Con2 ...  or  data Name where (GADT)
decls = re.findall(
    r'^data\s+(\w+)(?:\s+\w+)*\s*\n?\s*=\s*(.*?)(?=\n(?:data |type |class |newtype |instance |deriving |\w+\s*::|\Z))',
    src, re.MULTILINE | re.DOTALL)

# Also match record-style and simple enums
for name, body in decls:
    body = body.strip()
    # Clean up comments and pragmas
    body = re.sub(r'--.*', '', body)
    body = re.sub(r'\{-.*?-\}', '', body, flags=re.DOTALL)

    cons = [c.strip() for c in re.split(r'\n\s*\|', body) if c.strip()]
    if not cons:
        continue

    # Check if enum (all constructors have no fields)
    is_enum = all(re.match(r'^\w+$', c) for c in cons)

    # Check if record
    has_records = any('{' in c for c in cons)

    if is_enum:
        print(f'enum {name} {{')
        for c in cons:
            print(f'  {c}')
        print('}')
        print()
    elif has_records and len(cons) == 1:
        print(f'type {name} {{')
        fields = re.findall(r'(\w+)\s*::\s*([^,}]+)', cons[0])
        for fname, ftype in fields:
            gtype = hs_type(ftype.strip())
            print(f'  {fname}: {gtype}')
        print('}')
        print()
    else:
        # Union or object with constructors
        cnames = [re.match(r'(\w+)', c).group(1) for c in cons if re.match(r'(\w+)', c)]
        if len(cnames) > 1:
            print(f'union {name} = ' + ' | '.join(cnames))
        elif cnames:
            print(f'type {name} {{ # single constructor: {cnames[0]} }}')
        print()

def hs_type(t):
    t = t.strip()
    t = re.sub(r'\(.*\)', '', t)  # remove parens
    t = re.sub(r'\[(\w+)\]', r'[\1]', t)
    mapping = {
        'String': 'String', 'Text': 'String',
        'Int': 'Int', 'Integer': 'Int', 'Word': 'Int',
        'Float': 'Float', 'Double': 'Float', 'Rational': 'Float',
        'Bool': 'Boolean', 'Char': 'String',
        'ByteString': 'String', 'Bytes': 'String',
    }
    for k, v in mapping.items():
        if t == k:
            return v
    if t.startswith('Maybe '):
        return hs_type(t[6:])
    if t.startswith('['):
        inner = t[1:-1] if t.endswith(']') else t[1:]
        return f'[{hs_type(inner)}]'
    return t.split()[0] if t else 'String'
" 2>/dev/null
}

for thfile in "$OUTDIR"/th-syntax-*.hs; do
  [ -f "$thfile" ] || continue
  ver=$(basename "$thfile" | sed 's/th-syntax-\(.*\)\.hs/\1/')
  gqlfile="$OUTDIR/th-schema-${ver}.graphql"
  echo "# GHC $ver Template Haskell AST as GraphQL Schema" > "$gqlfile"
  echo "# Auto-generated by extract-th-schemas.sh" >> "$gqlfile"
  echo "" >> "$gqlfile"
  python3 "$SCRIPTDIR/hs2graphql.py" "$thfile" >> "$gqlfile"
  types=$(grep -c '^type \|^enum \|^union ' "$gqlfile")
  echo "$ver: $types GraphQL types"
done

echo ""
echo "=== Diff summary across versions ==="
files=("$OUTDIR"/th-schema-*.graphql)
prev=""
for f in "${files[@]}"; do
  ver=$(basename "$f" | sed 's/th-schema-\(.*\)\.graphql/\1/')
  if [ -n "$prev" ]; then
    added=$(diff "$prev" "$f" | grep '^>' | wc -l)
    removed=$(diff "$prev" "$f" | grep '^<' | wc -l)
    pver=$(basename "$prev" | sed 's/th-schema-\(.*\)\.graphql/\1/')
    echo "$pver → $ver: +$added -$removed lines"
  fi
  prev="$f"
done

echo ""
echo "Done. Schemas in $OUTDIR"
